### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by keough99** [Dabblecraft2DevTeam/NavyCraft#1]
Hi Maximuspayne and premejo,
I noticed that both of you have watched this repository.
I was wondering if you both have become interested? 
Your probably wound earring where it came from, it came from premejo's Navycraft repository,
(This is the reupload end version the other one the code broke during development)
This is a improved version I hope to improve it more and squash all bugs and fix lag issues

**Comment by keough99** [comment]
This is the broken version
https://github.com/Dabblecraft2DevTeam/Naval-Stuff

**Comment by Maximuspayne** [comment]
Hello Keough99,

Did you have a question for me something about torpedos?

Maximuspayne

**Comment by Maximuspayne** [comment]
Hello Keough99,

I'm a little unfamiliar with your project here or your background, but I'm
thinking that I might start helping clear things up by giving you a little
introduction to the plugin.

NavyCraft is of course a fork of Movecraft, not of Movecraft2 or 3 but of
the original one many years ago. Yogoda I think was the original author,
and Sycoprime took over after him. By the time I came around the plugin was
abandoned, vehicle turning was disabled because it had some glitches and
there were numerous other bugs. I was an author for Movecraft briefly many
years ago, I was on a plugin page as a developer for it when I fixed
rotation and a few other bugs.

But then I began adding features specific to our own server, Naval Battle
zone. These features were always highly experimental and coded specifically
to NBZ. Although I had always wanted to release a public version of my
work, I held back because the code became a bit of a jumbled mess that
needed fixing up, and to be more configurable. I became fully dedicated to
programming for NBZ, and the plugin developed quite a lot. Although it
still has a few similarities, like the vehicle detection algorithm is
mostly original, vast sections of the other code were changed over time.
Our Movecraft became very different from the original Movecraft, and near
the end of NBZ I had renamed our plugin from Movecraft to Navycraft to
finalize the differences.

Another important plugin that I took over was AimCannon. AimCannon was
originally developed by another author (I don't remember the name but I
think it should be in it's plugin.yml) and open source. The original
AimCannon provided just a single barrel working cannon, and I had improved
upon it to add many other types of weapons. AimCannon and NavyCraft have a
strong dependency between them, and it was my intent to eventually merge
the plugins into one, but I had not finished this yet. AimCannon is now
called AimCannonNC, all of it's original code had to be replaced as the
original was not thread-safe. AimCannonNC and NavyCraft have to both be
included with each other, they cannot work alone.

I don't know how much you had dealt with the current day Movecraft plugins
(not that I have tried them very much myself), or how much if ever you have
played on NBZ and know about what our plugins did, but it is important to
note there are some very major differences between them. I'm going to make
you a brief list of the major features and differences of plugin, in case
it might help you understand it better.

Features of Navycraft
1. Realistic movement/momentum system - Movecraft originally had a right
click to move interface for your vessel. This works fine for very small
servers, but having all of the players try to move at the same time would
lag up the server, and also its kind of unfair and very difficult to hit a
player with a cannon when they can instantly dodge with the right-click
movement. I replaced this with a more realistic movement system, ships
actually have momentum and need time to speed up, slow down, and turn.
Ships don't move when the players right click, but instead move on a timer
set by the server.

2. Server global movement timer - Scheduled as a synchronous task, the
server has particular schedule it follows for updating all of the vehicles.
In order to better handle the chaos of having many players drive many
vehicles at the same time, the server only updates certain vehicles on
every server tick. Depending on server load, on each server tick it will
iterate through all of the active vehicles on the server, and update one or
several of them. There are many ways to fine tune this system, and what I
had working seemed to help when we had lots of vehicles going.

3. Improved physics and features - Navycraft models much more. All blocks
in the game have custom weight and strength values programmed into them.
Ships and submarines have buoyancy and will sink lower in the water the
heavier they are, and will also sink if they take on too much water. Engine
signs are needed to power your vehicles, and different engines provide
different acceleration and speeds. Aircraft need to reach takeoff speed and
maintain it to fly. Sign equipment allows for functioning radars, sonars,
status displays, periscopes, And more!

4. Scoring, ranking, and economy system - Integration into Essentials and
GroupManager needed for these systems (they are not optional unfortunately,
but that can be fixed). When ships sink, players get killed, planes crash,
etc., the credited player is rewarded with rank points and money. Rank
points earn players ranks, which controls their daily pay and shipyard
rewards. Money is used to spawn ships, and players have to pay for their
equipment.

5. Vehicle Weapons - Cannons, double and triple barrel cannons, torpedoes
(Mk1, 2, and 3), depth charges (Mk 1 and 2), and AA-guns are some of the
weapons available. AimCannonNC controls all of the weapons except the
AA-guns. AimCannonNC uses a block detection interface that centers around a
Block Dispenser (Navycraft usually centers around signs instead).

6. Shipyard System - On NBZ, we used Navycraft to develop a convenient
shipyard system for our players. In a protected shipyard world, players
would automatically claim plots that only they had permission to, where
they could design the ship, sub, plane, or tank of their dreams. They could
then spawn their design in the main world (for a price) and still have
their protected copy in the shipyard to further modify and produce more
from.


So that is only a SHORT list of what makes NavyCraft different from
MoveCraft. All of the actual plugin coding was done by me. Premejo was our
server administrator, he provided NBZ with their server and worked hard to
keep it running. We also had Digitaldave and a staff of players who helped
us maintain the worlds and do some of the admin work with the other plugins
we used on the server. By around the time Naval Battle Zone had shut down,
I gave permission to Premejo to post the plugins in hopes of finding other
people who want to continue work on it.

In terms of moving forward, let me break down some of the issues that I
know of that need to be addressed...

1. Lag and Errors - As you mentioned lag needs worked on with the plugin.
The main reason for lag in the plugin results from the fact that we are
trying to change so many blocks at once, if you change too many blocks at
once, the server tends to choke, and errors sometimes happen. One error
that was driving me crazy is the "Sign not found error", this is actually a
client side error, meaning it can't be stopped from the server, From what I
can gather, it results from the server and client not quite being
completely synchronized yet (the client is still expecting to find a sign
at the place the ship was before it moved, but it isnt). The ordinary
minecraft server was simply not designed to support changing so many blocks
so quickly. I believe the solution lies in getting into the Minecraft NET
code and manually sending (and perhaps altering) packets. This is a bit
beyond my abilities, but I did find some open source code where another
plugin author manually sends a packet and I tried to adopt it as well...and
it seemed like it might of actually helped, it seemed like the moving ship
would update faster visually, and also it stopped the "Sign not found
error"...but it had one big drawback. Whenever I used it, the other players
(and other entities) who were standing on the ship would seem to disappear.
They were there but you could not see them anymore, for some reason
manually calling a packet chunk update would interfere in the client
displaying to you the other players and entities. I was not able to figure
this out, but I do believe the solution lies in NavyCraft modifying the
chunk updating/packet sending process to better suit its needs. I wanted to
try getting in touch with some developers who might have the knowledge to
help.

2.Code sloppiness and customizability - As I said before, the plugin had
always been highly experimental, and unfortunately I never took the time to
go back to clean things up and to make the plugin ready for public release.
For example, in multiple places, the plugin is specifically coded to do
certain things only in "warworld1" the main world, or the shipyard world
"shipyard". This along with many other options are hardcoded, but would be
better put into a configuration file instead. Every time minecraft adds new
blocks to the game, these have to be manually added into the java code as
well, with their strength and weight values (a block library config file
would be much better for that). Because the code consists of the work of at
least three different authors slapped together over time, it is a confusing
mess for sure. There are many deprecated and no longer used methods in the
code that need to be watched out for, and marked deprecated or even removed.

3. Navycraft and AimCannon merger - Since these mods depend on each other
so much, I feel like they just need to be fully combined into one for
better ease of use. Or, if a modular design is desired (use only NavyCraft
for ship movement but don't want any weapons), it needs to be made in such
a way that they can function modularly.

Anyway, I think that is enough for now...hopefully some of this information
will be of help. I would be happy to try to answer any questions you have
or try to assist if I am able.

Maximuspayne

**Comment by keough99** [comment]
I was a player on nbz for a while it was my favorite server but then I got busy with my own, when I heard nbz got shut down I wanted to try to continue nbz on my server but in a different way, currently this version is the only one that has been cleaned up a bit and is updated and can be moved forward with the versions of minecraft easily, that actually works.

I knew of some of these issues the lag issue has actually been partially fixed by being updated to the latest version of minecraft and the unable to locate sign is no longer an issue I think it was fixed in 1.9.

About the torpedos and depth charges and bomb droppers,
When I try to use then I get "you are in a protected region" I changed the world names in the code but still got this message my dev tried to fix it and he has no clue about fixing it.
I moved the AimCannonNC code to maven yesterday to see if that has fixed it I have not tested it yet but will soon.

I have big plans to continue your work, I will invite you to the organization so if you would like to help you may.

Thank you,
keough99

**Comment by keough99** [comment]
Also is there a better way of communication other than github issues that you would prefer?

**Comment by Maximuspayne** [comment]
Hello,

Sorry for the delay in reply, but I finally got my programming stuff set up
again, and I got a copy of your code to look at. As for the protected
region issues, its because that code is contained in AimCannonNC. All of
the weapon systems (with the exception of the AA-Gun) are controlled by the
AimCannonNC plugin, and it has world checks of its own. The "Applying fix
...512" message that spams in console can easily be disabled in the plugin
as well, its a debug message that was never removed. I also noticed a minor
bug that sometimes when using the gold sword it would double click your
speed changes, it has to do with them adding main hand and off hand
capabilities and it was double triggering the event, I got that fixed. I'm
going to try to keep on working and see about integrating a better config
that allows easier world name changing. I'll work on commiting my changes
soon too.

Maximuspayne

**Comment by keough99** [comment]
I know about the separate region checks for worlds I changed it in the code but I'm still having an issue. Here's a link to the repository https://github.com/Dabblecraft2DevTeam/AimCannon
My dev tried updating the world guard checks but to no fix I tried doing fixes to the best of my current abilities with Java but with issues still. I pretty sure I changed all the world names.

**Comment by keough99** [comment]
I have an idea for the plugin that I think might be a good addition. Maybe have it so the plugin supports either pex or group manager?

**Comment by Maximuspayne** [comment]
I did notice that GroupManager was a now outdated mod. I will work on
removing it's dependency and implementing pex instead.

**Comment by keough99** [comment]
For better communication on the development of the plugin instead of using github issues,
Here's the invite link to the staff discord server for my server, https://discord.gg/ERFteaZ it doesn't require any account to be made. You don't have to join it but I think it's better than using a github issue.

**Comment by keough99** [comment]
I seen dwings video on your conversation on Skype I have decided to throw away the distrust of navalclash. And help you with your idea on a network type thing you suggested I think I can bring a lot to the table as I have the resources to help your idea come true. Let me know I would like to talk to you more on this

**Comment by Maximuspayne** [comment]
Yeah i've just been trying to catch up on what all is going on, lol. I only
learned of the existence of Naval Clash yesterday, and they are trying to
get me to help work with them. I am intrigued but I do realize there is
apparently at least a couple of different servers out there who are in
disagreement. I'm personally for trying to keep a version of the plugin
public for all, but I am kind of interested in some of their ideas and
might consider other options as well. I really haven't made any decisions
yet on anything though, besides just the general direction I would like to
take the plugin.

**Comment by keough99** [comment]
There's been distrust because all the sides have been throwing arguments and such at each other causing a rip in the community. It buggy me to see a community this devided.
There's is a main key issue in what's happened and that capitalism as that droopystarfish sees that he can make lots of money and is pretty much setting in motion what other servers with the plugin would probably compete to do, And as pretty much most people know capitalism and minecraft don't mix. My server has the plugin and is the only one that's neutral and is doing its own thing instead of being a copy of nbz my server is doing a role play side of things using the plugin but with larger role play elements with a whole lore and story line.

I have been very reluctant to talk about what's happened so far because ATM it's a very sensitive subject.

All that aside I would like to talk to you about the future of this plugin and maybe what we can do to improve the plugin. Nbz has actually shown me what can be done and has made me stride for not giving up on my own server.

**Comment by keough99** [comment]
The other servers who have the plugin are in major disagreement and I suspect navalclash is trying to capitalize on it because all I hear from them is how much money droopystarfish can make.

I've been reluctant to talk about the drama that's gone on and still am because of how sensitive of a subject it is.

All that aside I would like to talk to you about the future of the plugin

**Comment by premejo** [comment]
Just so we can keep a level head here.  What kind of plans are these other
servers talking about that would allow them to make all this money?  Do
they even have a plan?

**Comment by keough99** [comment]
the only one i hear about the money stuff is naval clash the one thing i heard is droopystarfish buying out the rights to everything and basically running off with it to make money but thats all i know

**Comment by premejo** [comment]
So no real hard facts..  All speculation.  Why do so many people think
there is so much money in hosting these servers?!  What is a lot of money?
Hundreds?  Thousands? Tens of thousands?!  From my experience hosting my
server, it was a struggle to get donations.  Not only did you have to
adhere to what Mojang/Microsoft wanted, but you also had to depend on
sporadic random donations from players.  Either hoping people donate, or
come up with something that people will donate for by means of some sort of
rewards system.

**Comment by keough99** [comment]
i know i have experience with servers and i know that capitalism and minecraft dont mix at all. infact i dont play on minigame servers much and at one time never did because it was all this capitalism stuff and this pay to win stuff that tons of people fell for and paid tons of money.
but to quote what droopystarfish said in the video "i have made servers then sold them for tons of money"
but from the speculation ive heard and comments ive seen droopy may do the opposite.

**Comment by premejo** [comment]
You may need to specify exactly you mean by droppystarfish may do the
opposite.  But I tend to gravitate towards your beliefs on capitalism and
minecraft servers.  In fact, I believe that NBZ/NavyCraft will suffer more
in this environment than one that is more open source and attracts more
creativity/engineer minded players. I like how you connect the capitalism
type server with "tons of people falling for the pay to win stuff".  It
makes me think that these type of servers will attract the most foolish of
players.  Players that won't be able to contribute to the ideals that has
made NavalBattlezone/Navycraft great.  But this also makes me think that in
order for NavyCraft to succeed, we may need those servers to pull those
players away from the server that is more focused on continuing the growth
of the loyal community of NBZ and its ideals.  I know that I am distracted
by those players (well players in general).  I am the type of person who
needs peace and quiet to really focus on creating something great.  So I
guess my point is that while I may side with your cause, there may still be
need to work with "competitors" to further the real goal of NBZ and its
community.

**Comment by keough99** [comment]
i like the fact about open source thats why im keeping this repository on my github and not closed sourcing it. i dont like to see a community so divided like nbz has become from all the drama and stuff.
i like maximuspaynes idea that he said about the servers with navycraft working together to achieve a common goal i think its completely possible but in order to make it possible we would have to make all sides talk to each other peacefully and lay down a foundation.

**Comment by premejo** [comment]
That sounds like a good plan.  Max and I will be working on this.

**Comment by Maximuspayne** [comment]
I'm still here Keough. I'm working hard on getting the configurable worlds
done and hopefully the group manager fix. Once those are done I will get it
posted to Github for you.

**Comment by Maximuspayne** [comment]
Here we go!
https://github.com/Maximuspayne/NavyCraft-Max.git

It is a very rough version of course, but I believe it is ready for some
testing. I fully integrated AimCannon into NavyCraft in this update, you no
longer need to have AimCannonNC plugin, it is now all in NavyCraft...the
other dependencies are still the same (will work on getting rid of
GroupManager next).

Configurable world name and multiple worlds is now possible. After running
the updated plugin it will add two new entries into the navycraft.xml file,
EnabledWorlds and BattleWorlds. EnabledWorlds is all the worlds that you
want the weapons and everything to work in, BattleWorlds is worlds meant
for the official battles (need to be listed in both). The rank points
aren't working quite right with this new system, and needs changed with
GroupManager anyway. It is theoretically possible to have multiple official
battle worlds now, although this feature is completely untested, and you
could still only run one battle at a time. Lots of testing and more work is
needed of course.

**Comment by keough99** [comment]
Thank you I will get it integrated with this repository after i have it tested

**Comment by keough99** [comment]
I'm not sure if you fixed this issue or not but with the AimCannon turrets the rotation of stairs wasn't saved properly and would be in all sorts of directions

**Comment by Maximuspayne** [comment]
That will not have been fixed yet. The code for rotating cannons is
different from the code for rotating ships and therefore more dated and
doesn't work as well. Should be able to fix eventually.

**Comment by keough99** [comment]
I'll look into it for the rotation of the stairs. I have a question about the official battle system. When you added the thing in the config for battle worlds did you put a section for the cords of the battle arenas?

**Comment by keough99** [comment]
I'll be leaving for tomorrow for 4 weeks on vacation however I will be able to check github while I'm gone

**Comment by keough99** [comment]
Can you send a pull request of the changes you've made to navycraft to this repository if possible?

**Comment by Maximuspayne** [comment]
Hey Keough,

I wanted to keep the work on my own repository, you can get it here
https://github.com/Maximuspayne/NavyCraft2-Lite
Feel free to clone/fork it whatever.

I also have a Spigot page now I am using to post my updates and news
https://www.spigotmc.org/resources/navycraft-lite.42297/

**Comment by keough99** [comment]
On what commit did you remove the rank and battle systems?

**Comment by keough99** [comment]
Hello max. I would like to talk to you on discord or Skype or through email if possible. As I have a few concerns I would like to discuss privately and not In a GitHub issue

**Comment by Maximuspayne** [comment]
Hey keough, talk to me on skype if you can. Solmex has my contact.

**Comment by keough99** [comment]
I sent a contact request to 2 skype accounts. Not sure exactly which one is yours. My skype name is identical to my github name. When you accept just say hey Keough it's max so I know which one. I'm being cautious currently. As of what's happening currently so that's why I sent the contact request to 2 skype accounts
